openapi: '3.0.1'
info:
  title: 'valorant-match-data-api-internal'

paths:
  /test:
    get:
      responses:
        '200':
          description: Successful response
      # x-amazon-apigateway-policy:
      #   Version: '2012-10-17'
      #   Statement:
      #     - Effect: Deny
      #       Principal: "*"
      #       Action: execute-api:Invoke
      #       Resource: execute-api:/*/*/*
      #       Condition:
      #         StringNotEquals:
      #           aws:SourceArn:
      #             Fn::Sub: "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${ValorantMatchDataApiEntryFunction}"
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ ApiGatewayInvokeRole, Arn ]
        httpMethod: POST
        type: aws_proxy
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${TestInternalApiFunction}/invocations