openapi: '3.0.1'
info:
  title: 'My API'

paths:
  /valorant-match-data-api-entry:
    post:
      responses:
        '200':
          description: Successful response
        '401':
          description: Invalid request signature
      x-amazon-apigateway-integration:
        credentials:
          Fn::GetAtt: [ ApiGatewayInvokeRole, Arn ]
        httpMethod: POST
        type: aws_proxy
        uri: 
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${ValorantMatchDataApiEntryFunction}/invocations