AWSTemplateFormatVersion: 2010-09-09
Description: >-
  valorant-match-data-api-internal

Transform:
- AWS::Serverless-2016-10-31

Globals:
  Api:
    OpenApiVersion: 3.0.1
  Function:
    Runtime: nodejs18.x
    Timeout: 30
    MemorySize: 128
    Architectures:
      - x86_64

Resources:
  ValorantMatchDataApiInternal:
    Type: AWS::Serverless::Api
    Properties:
      Name: valorant-match-data-api-internal
      StageName: dev
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: dist/open-api-specification.yaml

  TestInternalApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/test/
      Environment:
        Variables:
          VALORANT_MATCH_DATA_TABLE: 
            Fn::ImportValue: VALORANT-MATCH-DATA-TABLE-NAME
      FunctionName: !Sub ${AWS::StackName}-test-function
      Handler: handler.handler
      Role: !GetAtt StatGenerationLambdaRole.Arn

  TestInternalApiFunctionLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${AWS::StackName}-test-function'
      RetentionInDays: 30
  
  StatGenerationLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: stat-generation-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowStatGenerationLambdaToAssumeRole
            Effect: Allow
            Action: 
              - sts:AssumeRole
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - PolicyName: WriteToLogGroup
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
        - PolicyName: DynamoDbAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:Query
                Resource:
                  - Fn::ImportValue: VALORANT-MATCH-DATA-TABLE-ARN

  ApiGatewayInvokeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowApiGatewayServiceToAssumeRole
            Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - apigateway.amazonaws.com
      Policies:
        - PolicyName: InvokeFunctions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !GetAtt TestInternalApiFunction.Arn

Outputs:
  InternalApiBaseUrl:
    Value: !Sub "https://${ValorantMatchDataApiInternal}.execute-api.${AWS::Region}.amazonaws.com/dev/"
    Export:
      Name: INTERNAL-API-BASE-URL
