export const GARRIN_NAME = 'Jetpack'
export const GARRIN_SMURF_NAME = 'VELOCITYHEAVENS'
export const JAC_NAME = 'ItsJustMono'
export const LLOYD_NAME = 'Cornishiwa'
export const LLOYD_SMURF_NAME = 'BitterSun'
export const LLYWELYN_NAME = 'Llywelyn'
export const LLYWELYN_SMURF_NAME = 'Cowderoy'
export const MABON_NAME = 'Mabyo'
export const MABON_SMURF_NAME = 'seb0n'
export const OWAIN_NAME = 'BradleySwiggins'
export const SION_NAME = 'GingerBinger'
export const SOPHIE_NAME = 'Scl'

export const GARRIN_TAG = '6350'
export const GARRIN_SMURF_TAG = '3606'
export const JAC_TAG = 'EUW'
export const LLOYD_TAG = 'EUW'
export const LLOYD_SMURF_TAG = 'EUW'
export const LLYWELYN_TAG = 'EUW'
export const LLYWELYN_SMURF_TAG = '2870'
export const MABON_TAG = 'EUW'
export const MABON_SMURF_TAG = 'EUW'
export const OWAIN_TAG = '9080'
export const SION_TAG = 'EUW'
export const SOPHIE_TAG = '7277'

export enum PLAYER_NAME {
  GARRIN = GARRIN_NAME,
  GARRIN_SMURF = GARRIN_SMURF_NAME,
  JAC = JAC_NAME,
  LLOYD = LLOYD_NAME,
  LLOYD_SMURF = LLOYD_SMURF_NAME,
  LLYWELYN = LLYWELYN_NAME,
  LLYWELYN_SMURF = LLYWELYN_SMURF_NAME,
  MABON = MABON_NAME,
  MABON_SMURF = MABON_SMURF_NAME,
  OWAIN = OWAIN_NAME,
  SION = SION_NAME,
  SOPHIE = SOPHIE_NAME
}

export const PLAYER_TAG_LOOKUP = {
  [GARRIN_NAME]: GARRIN_TAG,
  [GARRIN_SMURF_NAME]: GARRIN_SMURF_TAG,
  [JAC_NAME]: JAC_TAG,
  [LLOYD_NAME]: LLOYD_TAG,
  [LLOYD_SMURF_NAME]: LLOYD_SMURF_TAG,
  [LLYWELYN_NAME]: LLYWELYN_TAG,
  [LLYWELYN_SMURF_NAME]: LLYWELYN_SMURF_TAG,
  [MABON_NAME]: MABON_TAG,
  [MABON_SMURF_NAME]: MABON_SMURF_TAG,
  [OWAIN_NAME]: OWAIN_TAG,
  [SION_NAME]: SION_TAG,
  [SOPHIE_NAME]: SOPHIE_TAG
}

export const TEAM_NAMES_LIST = [
  GARRIN_NAME,
  GARRIN_SMURF_NAME,
  JAC_NAME,
  LLOYD_NAME,
  LLOYD_SMURF_NAME,
  LLYWELYN_NAME,
  LLYWELYN_SMURF_NAME,
  MABON_NAME,
  MABON_SMURF_NAME,
  OWAIN_NAME,
  SION_NAME,
  SOPHIE_NAME
]
